### ISSUE TITLE
Issues with IDA 7.4

### ISSUE THREAD

**Issue by recvfrom** [vrtadmin/CASC#29]
```
C:\Program Files\IDA Pro 7.4\plugins\casc_plugin.py: cannot import name GetIdaDirectory
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\python\2\ida_idaapi.py", line 622, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.4/plugins/casc_plugin.py", line 52, in <module>
    from idc import GetIdaDirectory
ImportError: cannot import name GetIdaDirectory
```

**Comment by recvfrom** [comment]
This gets CASC working again for now:

![image](https://user-images.githubusercontent.com/36489577/75928215-ebc72600-5e3b-11ea-858a-8179628bd6af.png)

From: https://www.hex-rays.com/products/ida/support/ida74_idapython_no_bc695/
