### ISSUE TITLE
parsing some code is causing traceback

### ISSUE THREAD

**Issue by etacheau** [vrtadmin/CASC#9]
For example parsing winmain subroutine from file wabmig.exe (from win7x64) 53A5EAFAAB88D5DBB24E6EEB5D9E0E12

```
main() function at 10033C8, named "_WinMain@16"
Marking typical code sequences...
Flushing buffers, please wait...ok
File 'C:\Users\admin\Downloads\wabmig.exe' has been successfully loaded into the database.
Compiling file 'C:\Program Files (x86)\IDA 6.95\idc\ida.idc'...
Executing function 'main'...
Compiling file 'C:\Program Files (x86)\IDA 6.95\idc\onload.idc'...
Executing function 'OnLoad'...
IDA is analysing the input file...
You may start to explore the input file right now.
-----------------------------------------------------------------------------------------
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] 
IDAPython v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
-----------------------------------------------------------------------------------------
Type library 'vc6win' loaded. Applying types...
Types applied to 3 names.
Using FLIRT signature: Microsoft VisualC 2-14/net runtime
Propagating type information...
Function argument information has been propagated
The initial autoanalysis has been finished.
Note: FormToPyQtWidget: importing 'sip' module into <module '__main__' from ''>
[CASCPlugin] Loaded 0 sub signatures
========================================
[CASC] Unsupported instruction parsing. Please open an issue in the git repo with the below information:
  EA: 0x16790762
  Instruction Size: 3
  Disassembly: setl    al
  Opcodes: 0f 9c c0
{'address': 16790762,
 'bytes': ['0f', '9c', 'c0'],
 'disassembly': 'setl    al',
 'disp': [''],
 'imm': [''],
 'modr/m': ['\x9c', {'mod': 2, 'reg': 3, 'rm': 4}],
 'opcode': ['\x0f', 'setl'],
 'prefix': [''],
 'sib': ['\xc0', {'base': 0, 'index': 0, 'ss': 3}]}
========================================
Traceback (most recent call last):
  File "C:/Program Files (x86)/IDA 6.95/plugins/clamav_sig_creator.py", line 1805, in data
    temp.mask_opcodes_tuple(mask_options)
  File "C:/Program Files (x86)/IDA 6.95/plugins/clamav_sig_creator.py", line 1222, in mask_opcodes_tuple
    self.mask_opcodes(self.mask_options)
  File "C:/Program Files (x86)/IDA 6.95/plugins/clamav_sig_creator.py", line 1208, in mask_opcodes
    data = self.parser.mask_instruction(instr.ea, mask_options)
  File "C:/Program Files (x86)/IDA 6.95/plugins/clamav_sig_creator.py", line 729, in mask_instruction
    instr = self.parse_instruction(ea)
  File "C:/Program Files (x86)/IDA 6.95/plugins/clamav_sig_creator.py", line 1085, in parse_instruction
    instr['disp'] = [disp, hex(struct.unpack(disp_str, disp)[0])]
struct.error: unpack requires a string argument of length 4
```

**Comment by demonduck** [comment]
fix can be found in dev commit 6751f9cea672b291da6937d8174460e5f280d58d
